<a href="https://colab.research.google.com/github/MohammedShahad7/Data-Science-/blob/main/Cleaning%20Text%20at%20Scale%20-%20String%20Data%20Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas as pd
import seaborn as sns
import numpy as np

In [57]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

In [58]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [59]:
# Observation: I expect numeric-only tickets to produce NaN, while tickets with letters or symbols will produce a prefix.

df['ticket_prefix'] = df['Ticket'].str.extract(r'^([^0-9]+)')

In [60]:
df['ticket_prefix'].isna().sum()

np.int64(661)

In [62]:
df['ticket_prefix']=df['ticket_prefix'].str.strip().str.upper()

In [63]:
df['ticket_prefix']=df['ticket_prefix'].fillna('Numeric')

In [66]:
df['ticket_prefix']=df['ticket_prefix'].str.replace('.','').str.replace('/','')

In [68]:
df['ticket_prefix'
]

0            A
1           PC
2        STONO
3      Numeric
4      Numeric
        ...
886    Numeric
887    Numeric
888         WC
889    Numeric
890    Numeric
Name: ticket_prefix, Length: 891, dtype: object

In [70]:
group=df.groupby('ticket_prefix')['Survived'].agg(
    survival_rate='mean',
    passenger_count='count'
).sort_values(
        'survival_rate',
        ascending=False
    )

group

               survival_rate  passenger_count
ticket_prefix
SC                  1.000000                1
SCAH BASLE          1.000000                1
SWPP                1.000000                2
FCC                 0.800000                5
PP                  0.666667                3
PC                  0.650000               60
SCAH                0.500000                2
PPP                 0.500000                2
SCPARIS             0.454545               11
STONO               0.444444               18
C                   0.400000                5
Numeric             0.384266              661
CA                  0.341463               41
WEP                 0.333333                3
LINE                0.250000                4
SOC                 0.166667                6
SOTONOQ             0.133333               15
WC                  0.100000               10
A                   0.071429               28
AS                  0.000000                1
CASOTON             0.000000                1
FC                  0.000000                1
FA                  0.000000                1
SCA                 0.000000                1
SCOW                0.000000                1
SOP                 0.000000                1
SP                  0.000000                1
SOPP                0.000000                3
SOTONO              0.000000                2

In [71]:
df.isna().sum()

PassengerId        0
Survived           0
Pclass             0
Name               0
Sex                0
Age              177
SibSp              0
Parch              0
Ticket             0
Fare               0
Cabin            687
Embarked           2
ticket_prefix      0
dtype: int64

In [72]:
df.dtypes

PassengerId        int64
Survived           int64
Pclass             int64
Name              object
Sex               object
Age              float64
SibSp              int64
Parch              int64
Ticket            object
Fare             float64
Cabin             object
Embarked          object
ticket_prefix     object
dtype: object