<a href="https://colab.research.google.com/github/MohammedShahad7/Data-Science-/blob/main/Duplicate%20Detection%20and%20Fuzzy%20Matching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd
import seaborn as sns
import numpy as np

In [44]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

In [45]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [46]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [47]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df['Age'] = df.groupby('Pclass')['Age'].transform(
        lambda x: x.fillna(x.median())
    )

    # Cabin - MNAR
df['has_cabin'] = df['Cabin'].notna().astype(int)

In [48]:
print((df['Fare']==0).sum())

15

In [49]:
df['Fare']=df['Fare'].replace(0,np.nan)

In [50]:
df['Fare']=df.groupby('Pclass')['Fare'].transform(
        lambda x: x.fillna(x.median())
)

In [51]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
has_cabin        0
dtype: int64

In [52]:
surname=df['Name'].str.split(',').str[0]

surname.head()

0       Braund
1      Cumings
2    Heikkinen
3     Futrelle
4        Allen
Name: Name, dtype: object

In [55]:
surname.value_counts().head()

Name
Andersson    9
Sage         7
Skoog        6
Panula       6
Carter       6
Name: count, dtype: int64